---
- name: Set up hosts
  hosts: all
  become: yes # Запускать задачи с привилегиями root/sudo
  tasks:
    - name: Stop and disable UFW service
      ansible.builtin.service:
        name: ufw
        state: stopped
        enabled: false
    - name: install traceroute
      ansible.builtin.apt:
        name: traceroute
        state: present
        update_cache: yes
    - name: Set up NAT on inetRouter
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: "iptables_rules.ipv4", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
        - { src: "iptables_restore", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
      when: (ansible_hostname == "inetRouter")
    - name: set up forward packages across routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
      when: "'routers' in group_names"
    - name: disable default route
      template: 
        src: 00-installer-config.yaml
        dest: /etc/netplan/00-installer-config.yaml
        owner: root
        group: root
        mode: 0644
      when: (ansible_hostname != "inetRouter")
    - name: add default gateway for hosts
      template: 
        src: "50-vagrant_{{ansible_hostname}}.yaml"
        dest: /etc/netplan/50-vagrant.yaml
        owner: root
        group: root
        mode: 0644
    - name: restart all hosts
      reboot:
        reboot_timeout: 600

  
